parameters:
    neo4j.graph_manager.class: Neo4jUserBundle\Manager\GraphManager
    neo4j.token_generator.class: Neo4jUserBundle\Security\Token\TokenGenerator

        
services:
    neo4j.graph_manager:
        class: %neo4j.graph_manager.class%
    neo4j.user_provider:
        class: Neo4jUserBundle\Security\User\UserProvider
        arguments: ['@neo4j.graph_manager']
    neo4j.token_generator:
         class: %neo4j.token_generator.class%
         arguments: ['@neo4j.graph_manager']